"""Initial migration (with product assignees)

Revision ID: 9aef43823139
Revises: 
Create Date: 2025-06-24 14:42:16.758956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aef43823139'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('assigned_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['assigned_to'], ['id'])

    # ### end Alembic commands ###
